//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFreamworkInDepth
{
    using System;
    
    public enum classification : byte
    {
        Sliver = 1,
        Gold = 2,
        Platnium = 3
    }
}
