//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFreamworkInDepth
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_card_details
    {
        public string customer_id { get; set; }
        public string card_id { get; set; }
        public System.DateTime issue_date { get; set; }
    
        public virtual customer_master customer_master { get; set; }
        public virtual library_card_master library_card_master { get; set; }
    }
}
