//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFreamworkInDepth
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_issue_details
    {
        public string issue_id { get; set; }
        public string customer_id { get; set; }
        public string movie_id { get; set; }
        public System.DateTime issue_date { get; set; }
        public System.DateTime return_date { get; set; }
        public System.DateTime actual_date_of_return { get; set; }
    
        public virtual customer_master customer_master { get; set; }
        public virtual movies_master movies_master { get; set; }
    }
}
