//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFreamworkInDepth
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_master()
        {
            this.customer_issue_details = new HashSet<customer_issue_details>();
            this.customer_card_details = new HashSet<customer_card_details>();
        }
    
        public string customer_id { get; set; }
        public string customer_name { get; set; }
        public int contact_no { get; set; }
        public string contact_address { get; set; }
        public System.DateTime date_of_regsitration { get; set; }
        public int age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_issue_details> customer_issue_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_card_details> customer_card_details { get; set; }
    }
}
