//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFreamworkInDepth
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KainthsouravEntities : DbContext
    {
        public KainthsouravEntities()
            : base("name=KainthsouravEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer_issue_details> customer_issue_details { get; set; }
        public virtual DbSet<customer_master> customer_master { get; set; }
        public virtual DbSet<library_card_master> library_card_master { get; set; }
        public virtual DbSet<movies_master> movies_master { get; set; }
        public virtual DbSet<CRUD> CRUDs { get; set; }
        public virtual DbSet<customer_card_details> customer_card_details { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
