//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFreamworkInDepth
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movies_master()
        {
            this.customer_issue_details = new HashSet<customer_issue_details>();
        }
    
        public string movie_id { get; set; }
        public string move_name { get; set; }
        public int release_Year { get; set; }
        public string language { get; set; }
        public int rating { get; set; }
        public int duration_in_mintues { get; set; }
        public string movie_type { get; set; }
        public string movie_category { get; set; }
        public string director_name { get; set; }
        public string lead_actor_name1 { get; set; }
        public string lead_actor_name2 { get; set; }
        public int rental_cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_issue_details> customer_issue_details { get; set; }
    }
}
